const postCardData = [
  {
    author: 'Jane Doe',
    profile: 'https://randomuser.me/api/portraits/women/50.jpg',
    title: 'PLP Graduation Event',
    description: 'Join us for the PLP graduation event this Friday! 🎉',
    images: ['https://images.unsplash.com/photo-1506744038136-46273834b3fb'],
    posted: '2 hours ago',
    specialization: 'Graduates',
  },
  {
    author: 'Mark Smith',
    profile: 'https://randomuser.me/api/portraits/men/51.jpg',
    title: 'Hackathon Winners',
    description: 'Congrats to the winners of the recent hackathon!',
    images: ['https://images.unsplash.com/photo-1465101046530-73398c7f28ca'],
    posted: '1 day ago',
    specialization: 'Hackathons',
  },
  {
    title: 'WhatsApp Group: Data Science Enthusiasts',
    author: 'Amina Yusuf',
    posted: '1 hour ago',
    specialization: 'Data Science',
    profile: 'https://randomuser.me/api/portraits/women/65.jpg',
    images: ['https://images.unsplash.com/photo-1519125323398-675f0ddb6308?auto=format&fit=crop&w=400&q=80'],
    description: 'Join our WhatsApp group for daily discussions and resources: https://chat.whatsapp.com/HCDZhcMA8zfEHn4ROnNMma',
  },
  {
    title: 'Telegram Group: Frontend Masters',
    author: 'Samuel Lee',
    posted: '10 minutes ago',
    specialization: 'Frontend Development',
    profile: 'https://randomuser.me/api/portraits/men/41.jpg',
    images: ['https://images.unsplash.com/photo-1515378791036-0648a3ef77b2?auto=format&fit=crop&w=400&q=80'],
    description: 'Looking for passionate frontend devs! Join our Telegram group: https://t.me/frontendmasters',
  },
  {
    title: 'WhatsApp Group: Machine Learning Projects',
    author: 'Fatima Bello',
    posted: '30 minutes ago',
    specialization: 'Machine Learning',
    profile: 'https://randomuser.me/api/portraits/women/68.jpg',
    images: ['https://images.unsplash.com/photo-1503676382389-4809596d5290?auto=format&fit=crop&w=400&q=80'],
    description: 'Collaborate on ML projects! Join our WhatsApp group: https://chat.whatsapp.com/HCDZhcMA8zfEHn4ROnNMma',
  },
  {
    title: 'Join Our Cybersecurity Telegram Channel',
    author: 'David Kim',
    posted: '3 hours ago',
    specialization: 'Cybersecurity',
    profile: 'https://randomuser.me/api/portraits/men/55.jpg',
    images: ['https://images.unsplash.com/photo-1465101046530-73398c7f28ca?auto=format&fit=crop&w=400&q=80'],
    description: 'Stay updated with the latest in cybersecurity. Telegram: https://t.me/cybersecnews',
  },
  {
    title: 'UI/UX Designers WhatsApp Group',
    author: 'Linda Okoro',
    posted: '6 hours ago',
    specialization: 'UI/UX Design',
    profile: 'https://randomuser.me/api/portraits/women/23.jpg',
    images: ['https://images.unsplash.com/photo-1517816743773-6e0fd518b4a6?auto=format&fit=crop&w=400&q=80'],
    description: 'Connect with other designers! WhatsApp: https://chat.whatsapp.com/HCDZhcMA8zfEHn4ROnNMma',
  },
];

export default postCardData;
